apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:abderr
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - name: command
      protocol: TCP
      port: 21
      targetPort: 21
    - name: active
      protocol: TCP
      port: 20
      targetPort: 20
    - name: passive
      protocol: TCP
      port: 30000
      targetPort: 30000